# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('WEBA', 'WebApplication'), ('DESK', 'Desktop'), ('MOBI', 'Mobile')], default='WEBA', max_length=4)),
                ('language', models.CharField(choices=[('PHP', 'PHP'), ('PYTH', 'Python'), ('RUBY', 'Ruby on Rails')], max_length=5)),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintains_apps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opcbase.App')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('domainname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(choices=[('on', 'OnSite'), ('EU', 'Europe'), ('AU', 'Africa')], default='EU', max_length=2)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realms_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opcbase.OS'),
        ),
        migrations.AddField(
            model_name='machine',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='opcbase.Realm'),
        ),
        migrations.AddField(
            model_name='instance',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='opcbase.Realm'),
        ),
    ]
