# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opcbase', '0002_auto_20161130_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255)),
                ('loginname', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealmType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='realm',
            name='state',
            field=models.CharField(choices=[('IN', 'Initializing'), ('WK', 'Working'), ('RE', 'Ready')], default='IN', max_length=2),
        ),
        migrations.AddField(
            model_name='realm',
            name='admins',
            field=models.ManyToManyField(related_name='admin_of_realms', to='opcbase.Avatar'),
        ),
        migrations.AddField(
            model_name='realm',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='opcbase.RealmType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realm',
            name='users',
            field=models.ManyToManyField(related_name='member_of_realms', to='opcbase.Avatar'),
        ),
    ]
